<a href="https://colab.research.google.com/github/Harsh3445/PFML-SEM-4/blob/main/pfml_week_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr1=[10,12,23,34,45]
arr2=[2,4,5,6,10]
a=np.array(arr1)
b=np.array(arr2)
print("original array")
print(a)
print(b)
print("\nVector addition")
print(a+b)
print("\nVector addition")
print(a*b)
print("\nVector multiplication")
print(a/b)
print("\nvector division")
print(a.dot(b))
print("\nscalar multiplication")
sclr=5
print("scalar value",sclr)
print("array=",a)
print("result=",a*sclr)

def my_dunc(x,y):
  if x>y:
    return x-y
  else:
    return x+y
print("\n numpy vectorized method")
print("array=",a)
print("result=",a*sclr)

original array
[10 12 23 34 45]
[ 2  4  5  6 10]

Vector addition
[12 16 28 40 55]

Vector addition
[ 20  48 115 204 450]

Vector multiplication
[5.         3.         4.6        5.66666667 4.5       ]

vector division
837

scalar multiplication
scalar value 5
array= [10 12 23 34 45]
result= [ 50  60 115 170 225]

 numpy vectorized method
array= [10 12 23 34 45]
result= [ 50  60 115 170 225]
