<a href="https://colab.research.google.com/github/Harsh3445/PFML-SEM-4/blob/main/python_numpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.array([[1,2,0,4],[4,-0,6,0],[2.6,0,7,8],[3,7,4,2]])
print("originalarray\n",arr)

originalarray
 [[1.  2.  0.  4. ]
 [4.  0.  6.  0. ]
 [2.6 0.  7.  8. ]
 [3.  7.  4.  2. ]]


In [ ]:
cond=arr>2
temp=arr[cond]
print(temp)

[4.  4.  6.  2.6 7.  8.  3.  7.  4. ]


In [ ]:
arr=np.array([1,2,3,4,5,6,7])
print("origun=inal array",arr)
print("every 2 element reversed array",arr[::-2])

origun=inal array [1 2 3 4 5 6 7]
every 2 element reversed array [7 5 3 1]


In [ ]:
cond=arr>2
temp=arr[cond]
print("elements greater than 2",temp)


elements greater than 2 [3 4 5 6 7]


In [ ]:
arr=np.array([[-1, 2, 0, 4], [4, -0.5, 6, 0], [2.6, 0, 7, 8], [3, -7, 4, 2.0]])
arr1=np.array([1, 2, 3])
arr2=np.array([4, 5, 6])
arr=np.concatenate((arr1,arr2))
print(arr1,arr2)
print("nJoined array:\n",arr)

[1 2 3] [4 5 6]
nJoined array:
 [1 2 3 4 5 6]


In [ ]:

arr=np.vstack((arr1,arr2))

print("dsstack\n",arr)

dsstack
 [[1 2 3]
 [4 5 6]]


In [ ]:
#Splitting array
arr= np.array([1, 2, 3, 4,5,6])
newarr= np.array_split(arr, 3)
print("\noriginal Array:\n",arr)
print("\nsplitted array:n",newarr)
#Displaying splitted array in another form
print("\nsplitted array in another form:\n")
print(newarr [0])
print(newarr[1])
print(newarr[2])


original Array:
 [1 2 3 4 5 6]

splitted array:n [array([1, 2]), array([3, 4]), array([5, 6])]

splitted array in another form:

[1 2]
[3 4]
[5 6]


In [ ]:
import numpy as np
#indexes where the value is 4:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
print("Original array:",arr)
x= np.where(arr == 4)
print("\nIndexes where the value is 4:\n",x)

Original array: [1 2 3 4 5 4 4]

Indexes where the value is 4:
 (array([3, 5, 6]),)


In [ ]:
import numpy as np
#indexes where the value is 4:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
print("Original array:",arr)
x= np.where(arr == 4)
print("\nIndexes where the value is 4:\n",x)


Original array: [1 2 3 4 5 4 4]

Indexes where the value is 4:
 (array([3, 5, 6]),)
