<a href="https://colab.research.google.com/github/Harsh3445/PFML-SEM-4/blob/main/WEE_3_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr = np.array([3, 2, 0, 1])
print("\nOriginal array:", arr)
print("\nSorted array:", np.sort(arr))
arr = np.array([[3, 2, 4], [5, 0, 1]])
print("\nOriginal array:", arr)
print("\nSorted array:", np.sort(arr))


Original array: [3 2 0 1]

Sorted array: [0 1 2 3]

Original array: [[3 2 4]
 [5 0 1]]

Sorted array: [[2 3 4]
 [0 1 5]]


In [ ]:
arr=np.array([3,2,0,1])
print("\noriginal array",arr)
print("\nSorted array",np.sort(arr))


original array [3 2 0 1]

Sorted array [0 1 2 3]


In [ ]:
arr = np.array([41, 42, 43,44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print("\nOriginal array:",arr)
print("\nFilter array:condition->42:",filter_arr)
print("\nNew array:",newarr)


Original array: [41 42 43 44]

Filter array:condition->42: [False False  True  True]

New array: [43 44]


In [ ]:
arr=np.array([1,2,3,4,5,6,7,])
x=np.where(arr%2==0)
print(*arr)
print( "\n",*x)

1 2 3 4 5 6 7

 [1 3 5]


In [ ]:
x=np.searchsorted(arr, 3, side='left')
print("Indexes where the value 3 should be inserted, starting from the right: 2")

Indexes where the value 3 should be inserted, starting from the right: 2
